### ISSUE TITLE
Unhandled message type: {"tag":"test"}

### ISSUE THREAD

**Issue by rabsef-bicrym** [tloncorp/landscape-apps#1018]
If types will be implemented later, but not prior to first release, please comment them so users can't poke and ruin the notebook post.

Preferable alternative: Leave them and let other designers maybe use them and allow the front end to ignore `inline`s that it doesn't like.

```
Error: Unhandled message type: {"tag":"test"}
    at Xp (http://localhost/apps/groups/assets/index.5ecbd790.js:1007:74497)
    at QH (http://localhost/apps/groups/assets/index.5ecbd790.js:67:53181)
    at Jq (http://localhost/apps/groups/assets/index.5ecbd790.js:71:8838)
    at Aq (http://localhost/apps/groups/assets/index.5ecbd790.js:71:955)
    at g1e (http://localhost/apps/groups/assets/index.5ecbd790.js:71:881)
    at Fb (http://localhost/apps/groups/assets/index.5ecbd790.js:71:732)
    at pP (http://localhost/apps/groups/assets/index.5ecbd790.js:69:10926)
    at http://localhost/apps/groups/assets/index.5ecbd790.js:67:38960
    at e.unstable_runWithPriority (http://localhost/apps/groups/assets/index.5ecbd790.js:56:3906)
    at Ag (http://localhost/apps/groups/assets/index.5ecbd790.js:67:38737)
```

**Comment by jamesacklin** [comment]
@rabsef-bicrym Is this still an issue for you?

**Comment by mrozanski** [comment]
Closing, happy to reopen if confirmed it's still valid.
