### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by bidmut-modmyn** [tloncorp/landscape-apps#1410]
threw an error while scrolling randomly thru a migrated chat.

```
TypeError: Cannot read properties of undefined (reading 'split')
    at gtt (http://localhost/apps/escape/assets/index.c84a4bf8.js:396:87035)
    at fR (http://localhost/apps/escape/assets/index.c84a4bf8.js:93:53297)
    at uae (http://localhost/apps/escape/assets/index.c84a4bf8.js:97:8857)
    at aae (http://localhost/apps/escape/assets/index.c84a4bf8.js:97:964)
    at V6e (http://localhost/apps/escape/assets/index.c84a4bf8.js:97:887)
    at Iw (http://localhost/apps/escape/assets/index.c84a4bf8.js:97:737)
    at h_ (http://localhost/apps/escape/assets/index.c84a4bf8.js:95:10947)
    at http://localhost/apps/escape/assets/index.c84a4bf8.js:93:39072
    at e.unstable_runWithPriority (http://localhost/apps/escape/assets/index.c84a4bf8.js:82:3899)
    at Nm (http://localhost/apps/escape/assets/index.c84a4bf8.js:93:38846)
```

**Comment by patosullivan** [comment]
This is an escape issue you should file it there: https://github.com/uqbar-dao/landscape-apps
