### ISSUE TITLE
notebook: deleting an old note in Tlon Hosting Support fails with sects error

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape-apps#1502]
I'm an admin and can't delete it. Nick wrote it and can't delete it either.

```
TypeError: Cannot read properties of undefined (reading 'sects')
    at vvt (https://zurbit.io/apps/groups/assets/index.6b96209d.js:1138:68854)
    at qH (https://zurbit.io/apps/groups/assets/index.6b96209d.js:93:53297)
    at Yie (https://zurbit.io/apps/groups/assets/index.6b96209d.js:97:8857)
    at Rie (https://zurbit.io/apps/groups/assets/index.6b96209d.js:97:964)
    at P6e (https://zurbit.io/apps/groups/assets/index.6b96209d.js:97:887)
    at _w (https://zurbit.io/apps/groups/assets/index.6b96209d.js:97:737)
    at UG (https://zurbit.io/apps/groups/assets/index.6b96209d.js:95:10947)
    at Kd (https://zurbit.io/apps/groups/assets/index.6b96209d.js:95:8466)
    at l8 (https://zurbit.io/apps/groups/assets/index.6b96209d.js:97:15965)
    at https://zurbit.io/apps/groups/assets/index.6b96209d.js:97:17629
```
<img width="792" alt="Screenshot 2022-12-14 at 3 51 56 PM" src="https://user-images.githubusercontent.com/441466/207740106-5e0dcbee-338b-4cab-a035-cc92d4d9da35.png">

**Comment by zalberico** [comment]
I no longer see the error when attempting to delete the note, but it still fails to delete.

I also see the posts next to each other now in different size squares.

<img width="1576" alt="Screenshot 2022-12-15 at 4 47 20 PM" src="https://user-images.githubusercontent.com/441466/207996972-231d24dc-c789-41ad-86b9-a10df0e0152b.png">

**Comment by zalberico** [comment]
@arthyn I was able to successfully delete this from the group host itself
