### ISSUE TITLE
groups: cannot read properties of undefined (reading 'sects')

### ISSUE THREAD

**Issue by romimalta** [tloncorp/landscape-apps#1513]
```
TypeError: Cannot read properties of undefined (reading 'sects')
    at Qy (https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:68:37959)
    at https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:1077:3618
    at Array.some (<anonymous>)
    at https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:1077:3602
    at Array.filter (<anonymous>)
    at _pe (https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:1077:3581)
    at Ope (https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:1077:5274)
    at qH (https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:93:53297)
    at Yie (https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:97:8857)
    at Rie (https://natnex-ronret.tlon.network/apps/groups/assets/index.6b96209d.js:97:964)
```

**Comment by romimalta** [comment]
just refreshed Groups tab...

**Comment by jamesacklin** [comment]
Seeing this as well on a ship with heavy subscriber load (like Romi's).

This error often appears while editing a group and changing channels from "Open to All" to "Members Can View." This also doesn't appear immediately -- often when you've made the change to a channel and wait a bit. (Again, I think subscriber load is the determining factor.)

You can repro on ~nibset-napwyn (info is in 1password, proxy locally if you wish).

**Comment by jamesacklin** [comment]
Possibly related to #1435 (we were looking for a repro).

**Comment by jamesacklin** [comment]
Also reported in #1519, happened on reconnect and was not in the channel editor.

**Comment by zalberico** [comment]
I have a consistent repro when trying to delete a notebook in Tlon Hosting Support: https://github.com/tloncorp/landscape-apps/issues/1502

**Comment by jamesacklin** [comment]
@arthyn ~nibset-napwyn is on `iq85j` of Groups.

**Comment by arthyn** [comment]
@zalberico I get a backend error not the one you saw
