### ISSUE TITLE
Cannot read properties of undefined (reading 'sects')

### ISSUE THREAD

**Issue by belisarius222** [tloncorp/landscape-apps#1533]
when I reloaded the page for a chat channel in a group, it got this and prompted me to make an issue
```
TypeError: Cannot read properties of undefined (reading 'sects')
    at Fee (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:1137:11460)
    at bR (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:93:53297)
    at r_ (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:93:62833)
    at bae (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:97:9740)
    at mae (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:97:964)
    at sSe (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:97:887)
    at Kw (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:97:737)
    at m_ (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:95:10947)
    at https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:93:39072
    at e.unstable_runWithPriority (https://rovnys.cataphract.us/apps/escape/assets/index.eaacb2cf.js:82:3899)
```

This was in EScape, so could be a frontend error there, not sure.

**Comment by jamesacklin** [comment]
Fixed by #1521
