### ISSUE TITLE
"undefined" is not valid JSON

### ISSUE THREAD

**Issue by crites** [tloncorp/landscape-apps#1588]
```
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at gmt (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:1136:28046)
    at bR (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:93:53297)
    at Sae (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:97:8857)
    at bae (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:97:964)
    at mSe (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:97:887)
    at zw (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:97:737)
    at m_ (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:95:10947)
    at ip (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:95:8466)
    at M8 (http://192.168.30.180:8080/apps/escape/assets/index.77809ac8.js:97:15965)
```

**Comment by jamesacklin** [comment]
@crites Thanks—did you hit this error in Escape, or Groups?
