### ISSUE TITLE
notebooks: editing a note with a bulleted list throws error

### ISSUE THREAD

**Issue by polrel-witter** [tloncorp/landscape-apps#1598]
```
RangeError: Invalid content for node bulletList: <listItem(paragraph("Excise comets from a guest li
    at eh.check (http://localhost:8080/apps/groups/assets/index.972692a0.js:68:57518)
    at http://localhost:8080/apps/groups/assets/index.972692a0.js:68:57866
    at Qe.forEach (http://localhost:8080/apps/groups/assets/index.972692a0.js:68:44012)
    at eh.check (http://localhost:8080/apps/groups/assets/index.972692a0.js:68:57853)
    at http://localhost:8080/apps/groups/assets/index.972692a0.js:168:5580
    at Array.forEach (<anonymous>)
    at http://localhost:8080/apps/groups/assets/index.972692a0.js:168:5566
    at Object.insertContentAt (http://localhost:8080/apps/groups/assets/index.972692a0.js:165:8054)
    at http://localhost:8080/apps/groups/assets/index.972692a0.js:168:4392
    at Object.insertContent (http://localhost:8080/apps/groups/assets/index.972692a0.js:165:7432)
```

**Comment by jamesacklin** [comment]
@polrel-witter Thanks. Where did you encounter this error? In a notebook?

**Comment by polrel-witter** [comment]
Yeah, it happens when I click "edit" on a note.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by polrel-witter** [comment]
A new note, but I pasted the text from a separate program (i think it was just Ubuntu's plain text editor) so it may be caused by some weird embedded formatting.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jamesacklin** [comment]
See #1646: this happens when editing a bulleted list within a bulleted list.
