### ISSUE TITLE
talk: p.replied.at is not a function

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#1644]
getting this when trying to view the general channel in th uf internal group

```
TypeError: p.replied.at is not a function
    at https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:1067:10294
    at HT (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:93:53205)
    at SR (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:93:61325)
    at $Z (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:97:10802)
    at TZ (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:97:957)
    at Cfe (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:97:883)
    at Ey (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:97:734)
    at OB (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:95:10926)
    at https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:93:38960
    at e.unstable_runWithPriority (https://u.tinnus-napbus.xyz/apps/talk/assets/index.2ca47717.js:82:3908)
```

```
> +vat %talk
%talk
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1a.6gfhh.oeeuq.4b5nn.nibtq.va6jd.cogfr.11i6o.2rg1f.sto1s.06sqf
  %cz hash:         0v1a.6gfhh.oeeuq.4b5nn.nibtq.va6jd.cogfr.11i6o.2rg1f.sto1s.06sqf
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %talk
  source aeon:      6
  kids desk:        ~
  pending updates:  ~
::
```

**Comment by jamesacklin** [comment]
@patosullivan Want to check this one out?

**Comment by patosullivan** [comment]
Which browser are you using, @tinnus-napbus ?
