### ISSUE TITLE
Following link for app installation spins forever, errors in javascript console

### ISSUE THREAD

**Issue by felzix** [tloncorp/landscape-apps#1736]
**Describe the bug, optionally with screenshots**

In the pals app, I click on the contact book link which loads (censored IP addr) `http://xx.xx.xx.xx/apps/grid/leap/search/direct/apps/~holnes/whom`

The spinner spins for at least several minutes with no end in sight. I see this error in the javascript console:
```
Uncaught (in promise) TypeError: Vt.subscribeOnce is not a function
    at Object.requestTreaty (index.250e712f.js:173:48204)
    at index.250e712f.js:184:8013
    at _A (index.250e712f.js:60:6703)
    at e.unstable_runWithPriority (index.250e712f.js:45:3923)
    at Rc (index.250e712f.js:56:38646)
    at Du (index.250e712f.js:60:6167)
    at _3 (index.250e712f.js:58:10803)
    at index.250e712f.js:56:38868
    at e.unstable_runWithPriority (index.250e712f.js:45:3923)
    at Rc (index.250e712f.js:56:38646)
```

In the urbit terminal, I see this. Not sure if it's related:
```
; ~batbex not responding still trying
; ~batbex is ok
; ~bex not responding still trying
; ~bex is ok
```

**Additional context:**
- Ship type: Planet I think? Is there an urbit terminal command to get this information?
- Instance type: self-hosted on linode, CLI
- OS/browser: Brave on Linux

I received a landscape update while writing this ticket. After it succeeded, I reloaded the web page but the behavior did not change.
```
>
kiln: downloading update for %landscape from ~lander-dister-dozzod-dozzod/%landscape
ames: czar zod.urbit.org: ip .35.247.119.159
eyre: canceling ~[//http-server/0v1h.q8ilg/38/6]
kiln: finished downloading update for %landscape from ~lander-dister-dozzod-dozzod/%landscape
clay: wait-for-kelvin, [need=[%zuse %417] have={[lal=%zuse num=416]}]
kiln: merge into %landscape succeeded
```

I also tried stopping and starting the urbit cli. Also no change in behavior.

**Comment by felzix** [comment]
I was able to get the contacts app by loading only the landscape, searching for ~holnes, then selecting the only app it listed, contacts.
