### ISSUE TITLE
Receiving error `Cannot read properties of undefined (reading 'content')` when I attempt to edit a notebook post I've authored

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#1791]
This appears correlated with the issues I'm seeing in #1790 

When I attempt to click "Edit Post", I'm getting the stack trace screen with the following error:

```
TypeError: Cannot read properties of undefined (reading 'content')
    at http://100.86.178.103:8083/apps/groups/assets/index.88c2dd90.js:254:18326
    at Array.filter (<anonymous>)
    at rS (http://100.86.178.103:8083/apps/groups/assets/index.88c2dd90.js:254:18254)
    at http://100.86.178.103:8083/apps/groups/assets/index.88c2dd90.js:254:19785
    at Array.map (<anonymous>)
    at $wt (http://100.86.178.103:8083/apps/groups/assets/index.88c2dd90.js:254:19765)
    at http://100.86.178.103:8083/apps/groups/assets/DiaryAddNote.d91870b2.js:3:73712
    at Object.useMemo (http://100.86.178.103:8083/apps/groups/assets/index.88c2dd90.js:93:59255)
    at Fn.useMemo (http://100.86.178.103:8083/apps/groups/assets/index.88c2dd90.js:12:5954)
    at ua (http://100.86.178.103:8083/apps/groups/assets/DiaryAddNote.d91870b2.js:3:73675)
```

**Comment by jamesacklin** [comment]
@patosullivan Did we determine an old front-end was the issue?

**Comment by patosullivan** [comment]
I think that's right.

**Comment by jamesacklin** [comment]
@urcades Can you sync your Groups desk on this ship to ~marnec-dozzod-marzod and re-test?
