### ISSUE TITLE
s3: user can still send while image is uploading after paste

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#1921]
came across this and it gave me an error dialog and option to submit issue here. Happened when taking a screenshot and then pasting into a group chat in Talk and hitting enter.

```
TypeError: Cannot read properties of undefined (reading 'name')
    at https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:398:310307
    at Array.map (<anonymous>)
    at https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:398:310237
    at spe (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:97:6696)
    at e.unstable_runWithPriority (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:82:3886)
    at C0 (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:93:38710)
    at Ih (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:97:6157)
    at https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:97:6069
    at D (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:82:2923)
    at I.port1.onmessage (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:82:1550)
```

**Comment by thelifeandtimes** [comment]
Brave on MacOS, desk hash of `0vm.re785.tq37s.duuhf.chn8b.bgbtq.ttkg1.rlurv.htbhm.4rdbq.jc2cb`

**Comment by patosullivan** [comment]
Having trouble reproducing this one.

**Comment by thelifeandtimes** [comment]
I'll note i successfully added the screenshot after and subsequent s3 images had no issue. May have something to do with hitting send too quickly?

**Comment by thelifeandtimes** [comment]
Had this same thing pop up again:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/82244264/219789302-a39f7014-65aa-40b6-b714-939ac163b13b.png">

```
TypeError: Cannot read properties of undefined (reading 'name')
    at https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:398:310307
    at Array.map (<anonymous>)
    at https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:398:310237
    at spe (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:97:6696)
    at e.unstable_runWithPriority (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:82:3886)
    at C0 (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:93:38710)
    at Ih (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:97:6157)
    at https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:97:6069
    at D (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:82:2923)
    at I.port1.onmessage (https://sarlev-sarsen.rooftopdao.io/apps/talk/assets/index.8991638c.js:82:1550)
```

This time it happened when trying to respond to a chat in a thread with an image. Increasingly suspecting there is some sort of middling state wherein I have pasted the image w/ `ctrl + v` but if I hit `enter` before the S3 upload completed I get this error.

**Comment by thelifeandtimes** [comment]
confirming that this definitely happens when hitting enter too quickly after pasting something into the chat box.

**Comment by patosullivan** [comment]
I can repro this.
