### ISSUE TITLE
Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by crites** [tloncorp/landscape-apps#2073]
```
TypeError: Cannot read properties of undefined (reading 'match')
    at https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:161:11733
    at Object.useMemo (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:58:59152)
    at Jt.useMemo (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:40:5905)
    at Wx (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:161:11719)
    at ax (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:58:53207)
    at ZS (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:8852)
    at US (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:959)
    at f$ (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:887)
    at U1 (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:740)
    at n7 (https://hanmus-mapfun.tlon.network/apps/grid/assets/index.2d5b6b39.js:60:10912)
```

**Comment by patosullivan** [comment]
What were you doing at the time this occured? Which browser are you using?
