### ISSUE TITLE
Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by ericvrp** [tloncorp/landscape-apps#2078]
```
TypeError: Cannot read properties of undefined (reading 'match')
    at https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:161:11733
    at Object.useMemo (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:58:59152)
    at Jt.useMemo (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:40:5905)
    at Wx (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:161:11719)
    at ax (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:58:53207)
    at ZS (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:8852)
    at US (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:959)
    at f$ (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:887)
    at U1 (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:62:740)
    at n7 (https://bossug-divmeg.tlon.network/apps/grid/assets/index.2d5b6b39.js:60:10912)
```

**Comment by patosullivan** [comment]
Appears to be the same as https://github.com/tloncorp/landscape/issues/107, @jamesacklin

**Comment by ericvrp** [comment]
Arc browser on macOS. Can't remember what I was doing 😄

**Comment by jamesacklin** [comment]
Thanks.

@patosullivan I'll try to reproduce this morning, think it has to do with app search.
