### ISSUE TITLE
Cannot read properties of undefined (reading 'meta')

### ISSUE THREAD

**Issue by m-rio** [tloncorp/landscape-apps#2135]
```
TypeError: Cannot read properties of undefined (reading 'meta')
    at http://localhost/apps/groups/assets/index.f67c0ed6.js:1150:57081
    at Array.forEach (<anonymous>)
    at http://localhost/apps/groups/assets/index.f67c0ed6.js:1150:57046
    at Object.useMemo (http://localhost/apps/groups/assets/index.f67c0ed6.js:93:59210)
    at er.useMemo (http://localhost/apps/groups/assets/index.f67c0ed6.js:12:5954)
    at tmt (http://localhost/apps/groups/assets/index.f67c0ed6.js:1150:56997)
    at gR (http://localhost/apps/groups/assets/index.f67c0ed6.js:93:53252)
    at Nae (http://localhost/apps/groups/assets/index.f67c0ed6.js:97:8857)
    at Tae (http://localhost/apps/groups/assets/index.f67c0ed6.js:97:964)
    at DSe (http://localhost/apps/groups/assets/index.f67c0ed6.js:97:887)
```

**Comment by patosullivan** [comment]
What were you doing in the app when you saw this error, and was it in groups or talk?

**Comment by m-rio** [comment]
> What were you doing in the app when you saw this error, and was it in groups or talk?

I believe I tried to open a group and it crashed this way (don't recall the group). I was using "new" group

**Comment by jamesacklin** [comment]
No reproduction, closing for now.
