### ISSUE TITLE
Cannot read properties of null (reading 'memo')

### ISSUE THREAD

**Issue by tinnus-napbus** [tloncorp/landscape-apps#2196]
```
TypeError: Cannot read properties of null (reading 'memo')
    at zZe (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:1089:32915)
    at dR (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:93:53163)
    at SD (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:93:62674)
    at wJ (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:97:9730)
    at yJ (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:97:959)
    at z0e (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:97:885)
    at Nx (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:97:736)
    at ID (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:95:10926)
    at https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:93:38933
    at e.unstable_runWithPriority (https://u.tinnus-napbus.xyz/apps/talk/assets/index.4599e063.js:82:3886)
```

```
> +vat %talk
%talk
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
  base hash:        0ve.3r4jj.n5ish.n63h8.1qu3o.vkodt.dvhm9.4aisd.opm40.pub9c.5a1p3
  %cz hash:         0ve.3r4jj.n5ish.n63h8.1qu3o.vkodt.dvhm9.4aisd.opm40.pub9c.5a1p3
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~binnec-dozzod-marzod
  source desk:      %talk
  source aeon:      107
  kids desk:        ~
  pending updates:  ~[[%zuse 414]]
::
```

**Comment by jamesacklin** [comment]
Any recollection as to what you were doing in Talk at the time?

**Comment by tinnus-napbus** [comment]
I believe I had opened a chat channel, I think it crashed on loading a reference of some kind, I think a chat quote-reply

**Comment by patosullivan** [comment]
Without knowing more about the context, I'm guessing a subscribeOnce to grab the writ failed. We really ought to just grab the writs from pacts first and only use subscribeOnce to grab a writ if we can't find it in a pact. Making a PR for that.
