### ISSUE TITLE
Cannot read property 'writs' of undefined

### ISSUE THREAD

**Issue by ilyakooo0** [tloncorp/landscape-apps#2313]
```
TypeError: Cannot read property 'writs' of undefined
    at Ex (https://urbit.iko.soy/apps/groups/assets/index.8af1b904.js:45:44681)
    at Kl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:52884)
    at mf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:8723)
    at pf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:947)
    at yg (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:875)
    at rn (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:23:730)
    at sl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:21:10884)
    at https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:38716
    at e.unstable_runWithPriority (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:8:3811)
    at _r (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.3bfe057f.js:19:38494)
```

**Comment by patosullivan** [comment]
Hi, thanks for filing. What were you trying to do at the time this error occurred?

**Comment by patosullivan** [comment]
And could you provide the hash of your %groups desk? `+vat %groups` or from the "About Groups" section in the app.

**Comment by ilyakooo0** [comment]
the hash is `0v1o.pl7r7.if2k1.u2stu.gn3b4.7ctpm.f7sct.40rvk.tv4s9.ltt4t.tjavf`

**Comment by ilyakooo0** [comment]
i don't remember what i was doing
