### ISSUE TITLE
gallery: error+stack trace produced when attempting to post a text block to a gallery

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2314]
Ran into the following stack trace while attempting to add text to a gallery. The text was preformatted (on paste) as a "code block"-style of text:

```
Error: Unhandled message type: {"code":"Intro:\n \nAm, F, C...\nF, Em7, C, Em7, F\nEm7, C, Dm, F, G\n \nVerse:\n \nAm\nSomeday\n   C          Em7   F\nI know we'll meet again\n    Em7  C       Em7     F\nWithout knowing exactly when\n    G      C\nAnd until then\n     Dm           F       G\nTake care of yourself my friend\n \n                      Am\nIf you tell it to my heart\n                  F\nwhere would you start?\n           G\nWith that truth we shared\n        Am         F        G\nor the lies that drove us apart?\n \n                      Am\nIf you tell it to my heart\n                  F\nwhere would you start?\n           G\nWith that truth we shared\n        Am         F        C\nor the lies that drove us apart?\n \n                      Am\nIf you tell it to my heart\n                  F\nwhere would you start?\n           G\nWith that truth we shared\n        Am         F        G\nor the lies that drove us apart?\n \nOutro:\n \nC\nHea-a-a-art\n              G\nTell it to my heart\n \nAm, F, G, C (ad infinitum)"}
    at Rn (https://fabled-faster.arvo.network/apps/groups/assets/index.0d515f03.js:45:70330)
    at Kl (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
    at _r (https://fabled-faster.arvo.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38494)
```

The text I attempted to paste in:

```
Intro:
 
Am, F, C...
F, Em7, C, Em7, F
Em7, C, Dm, F, G
 
Verse:
 
Am
Someday
   C          Em7   F
I know we'll meet again
    Em7  C       Em7     F
Without knowing exactly when
    G      C
And until then
     Dm           F       G
Take care of yourself my friend
 
                      Am
If you tell it to my heart
                  F
where would you start?
           G
With that truth we shared
        Am         F        G
or the lies that drove us apart?
 
                      Am
If you tell it to my heart
                  F
where would you start?
           G
With that truth we shared
        Am         F        C
or the lies that drove us apart?
 
                      Am
If you tell it to my heart
                  F
where would you start?
           G
With that truth we shared
        Am         F        G
or the lies that drove us apart?
 
Outro:
 
C
Hea-a-a-art
              G
Tell it to my heart
 
Am, F, G, C (ad infinitum)
```

**Comment by urcades** [comment]
It now appears that I can't navigate to the channel in question, I get a similar error screen every time I click on the channel in the sidebar:

<img width="236" alt="Screenshot 2023-04-17 at 11 58 37 AM" src="https://user-images.githubusercontent.com/1195363/232543091-9926a7fc-8312-44e6-902a-f5a71989bc33.png">

**Comment by jamesacklin** [comment]
Blocker for v3.0.0, please fix
