### ISSUE TITLE
chat: unable to load talk/groups

### ISSUE THREAD

**Issue by alecananian** [tloncorp/landscape-apps#2331]
An update came through on my Tlon-hosted ship and I'm now unable to load Talk/Groups, just seeing error messages with the following stacktraces - it may be that `useCalm()` is returning `undefined`?

```
TypeError: Cannot destructure property 'disableWayfinding' of 'it(...)' as it is undefined.
    at Uj (https://sapdex-diflyx.tlon.network/apps/talk/assets/index.3cbecfe5.js:48:169471)
    at Ko (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at eo (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:62311)
    at ea (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:9576)
    at Js (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:935)
    at Qf (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:866)
    at sn (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:725)
    at mo (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:21:10863)
    at https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38697
    at e.unstable_runWithPriority (https://sapdex-diflyx.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:8:3835)
```

```
TypeError: Cannot read properties of undefined (reading 'disableNicknames')
    at Ce (https://sapdex-diflyx.tlon.network/apps/groups/assets/index.8f9ec6e5.js:45:36798)
    at Kl (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://sapdex-diflyx.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
```

**Comment by belisarius222** [comment]
Also won't load for me.  Same issue.

**Comment by belisarius222** [comment]
```
> +vat %groups
/sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
base hash:        0v1o.e4iqb.6nphs.rts8b.9l4qg.3aqpm.8lbkj.29e8j.dhe1r.bs5n5.di3or
%cz hash:         0v1o.e4iqb.6nphs.rts8b.9l4qg.3aqpm.8lbkj.29e8j.dhe1r.bs5n5.di3or
app status:       running
force on:         ~
force off:        ~
publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
updates:          remote
source ship:      ~binnec-dozzod-marzod
source desk:      %groups
source aeon:      130
kids desk:        ~
pending updates:  ~
> +vat %talk
/sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
base hash:        0v1k.142jt.poe28.av587.44sav.718kj.3ls5b.1t7c0.rrl6s.kv3u7.h6h0s
%cz hash:         0v1k.142jt.poe28.av587.44sav.718kj.3ls5b.1t7c0.rrl6s.kv3u7.h6h0s
app status:       running
force on:         ~
force off:        ~
publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
updates:          remote
source ship:      ~binnec-dozzod-marzod
source desk:      %talk
source aeon:      122
kids desk:        ~
pending updates:  ~
~rovnys-ricfer:dojo> 
```
