### ISSUE TITLE
Cannot destructure property 'disableWayfinding' of 'Je(...)' as it is undefined.

### ISSUE THREAD

**Issue by belisarius222** [tloncorp/landscape-apps#2332]
```
TypeError: Cannot destructure property 'disableWayfinding' of 'Je(...)' as it is undefined.
    at XN (https://rovnys.cataphract.us/apps/groups/assets/index.8f9ec6e5.js:48:303982)
    at Kl (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://rovnys.cataphract.us/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
```

**Comment by belisarius222** [comment]
Duplicate of https://github.com/tloncorp/landscape-apps/issues/2331
