### ISSUE TITLE
Cannot read properties of undefined (reading 'meta')

### ISSUE THREAD

**Issue by marisarow** [tloncorp/landscape-apps#2335]
```
TypeError: Cannot read properties of undefined (reading 'meta')
    at https://riprud-tidmel.tlon.network/apps/groups/assets/index.0d515f03.js:48:81359
    at Array.forEach (<anonymous>)
    at https://riprud-tidmel.tlon.network/apps/groups/assets/index.0d515f03.js:48:81324
    at Object.Jd [as useMemo] (https://riprud-tidmel.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:57586)
    at f.useMemo (https://riprud-tidmel.tlon.network/apps/groups/assets/@tlon/sigil-js.4fa95bd4.js:12:5789)
    at X3 (https://riprud-tidmel.tlon.network/apps/groups/assets/index.0d515f03.js:48:81275)
    at Kl (https://riprud-tidmel.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://riprud-tidmel.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://riprud-tidmel.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://riprud-tidmel.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
```

Getting this error after selecting create section, and then clicking outside of the new section

**Comment by patosullivan** [comment]
This was fixed in #2339
