### ISSUE TITLE
Cannot destructure property 'disableWayfinding' of 'it(...)' as it is undefined.

### ISSUE THREAD

**Issue by matthew-levan** [tloncorp/landscape-apps#2338]
```
TypeError: Cannot destructure property 'disableWayfinding' of 'it(...)' as it is undefined.
    at Uj (https://mastyr-bottec.coeli.network/apps/talk/assets/index.3cbecfe5.js:48:169471)
    at Ko (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at eo (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:62311)
    at ea (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:9576)
    at Js (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:935)
    at Qf (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:866)
    at sn (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:725)
    at mo (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:21:10863)
    at https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38697
    at e.unstable_runWithPriority (https://mastyr-bottec.coeli.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:8:3835)
```

**Comment by jamesacklin** [comment]
Same as #2331, @patosullivan?

**Comment by arthyn** [comment]
Should be

**Comment by patosullivan** [comment]
Yes.
