### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by ilyakooo0** [tloncorp/landscape-apps#2431]
All I did was open groups.

Desk hash: `0v11.kq88i.9hcnd.c1mei.b3mfo.4vgqd.r3qss.04st6.pimdi.p39ol.ajmpq`

```
TypeError: Cannot read property 'title' of undefined
    at https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:48:16464
    at Kl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at Zd (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:61688)
    at Ls (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:61273)
    at mf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:11906)
    at pf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
```

**Comment by patosullivan** [comment]
This was just at the index of groups, right? like `https://urbit.iko.soy/apps/groups/`, not some particular route?

**Comment by ilyakooo0** [comment]
Just https://urbit.iko.soy/apps/groups/ yields an error

But now it is different:

Encountered error:Cannot use 'in' operator to search for 'shut' in undefined
```
TypeError: Cannot use 'in' operator to search for 'shut' in undefined
    at Gd (https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:1:45332)
    at dn (https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:1:45449)
    at https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:48:12098
    at Kl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at Zd (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:61688)
    at Ls (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:61273)
    at mf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:11906)
    at pf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
```

**Comment by patosullivan** [comment]
Thanks. I've got what should be a fix for that here: https://github.com/tloncorp/landscape-apps/pull/2436

The first issue is much more difficult to track down since there are a lot of things named "title" throughout the app. If you see it again and can provide a way to reliably reproduce it let us know.
