### ISSUE TITLE
Cannot use 'in' operator to search for 'shut' in undefined

### ISSUE THREAD

**Issue by ilyakooo0** [tloncorp/landscape-apps#2439]
Desk hash: `0v11.kq88i.9hcnd.c1mei.b3mfo.4vgqd.r3qss.04st6.pimdi.p39ol.ajmpq`

This happens every other time I open groups.

```
TypeError: Cannot use 'in' operator to search for 'shut' in undefined
    at Gd (https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:1:45332)
    at dn (https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:1:45449)
    at https://urbit.iko.soy/apps/groups/assets/index.c13885b0.js:48:12098
    at Kl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at Zd (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:61688)
    at Ls (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:61273)
    at mf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:11906)
    at pf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
```

**Comment by ilyakooo0** [comment]
Duplicate of #2431
