### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape-apps#2469]
Got this after hitting send on a message containing a reply 

```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.onExit (https://urbit.hmiller.dev/apps/talk/assets/index.6d7465ae.js:45:40214)
    at Object.destroy (https://urbit.hmiller.dev/apps/talk/assets/index.6d7465ae.js:45:26587)
    at Zo.destroyPluginViews (https://urbit.hmiller.dev/apps/talk/assets/@tiptap/core.cc7cd36d.js:5:40336)
    at Zo.destroy (https://urbit.hmiller.dev/apps/talk/assets/@tiptap/core.cc7cd36d.js:5:42006)
    at Bg.destroy (https://urbit.hmiller.dev/apps/talk/assets/@tiptap/core.cc7cd36d.js:85:407)
    at https://urbit.hmiller.dev/apps/talk/assets/index.6d7465ae.js:40:5676
    at Zf (https://urbit.hmiller.dev/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:6429)
    at e.unstable_runWithPriority (https://urbit.hmiller.dev/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:8:3835)
    at st (https://urbit.hmiller.dev/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38475)
    at Ze (https://urbit.hmiller.dev/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:6033)
```

**Comment by jamesacklin** [comment]
@arthyn Enjoy the new `android` tag.

**Comment by patosullivan** [comment]
Can't repro. Have you seen this again?
