### ISSUE TITLE
Cannot destructure property 'title' of 'e' as it is undefined.

### ISSUE THREAD

**Issue by wca4a** [tloncorp/landscape-apps#2483]
```
TypeError: Cannot destructure property 'title' of 'e' as it is undefined.
    at ae (https://malmur-halmex.tlon.network/apps/talk/assets/grid.4818f5f1.js:1:1610)
    at Ko (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at ea (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:8695)
    at Js (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:935)
    at Qf (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:866)
    at sn (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:725)
    at mo (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:21:10863)
    at https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38697
    at e.unstable_runWithPriority (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:8:3835)
    at st (https://malmur-halmex.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38475)
```

**Comment by patosullivan** [comment]
Hi, what were you trying to do when you saw this error and which browser were you using?

**Comment by patosullivan** [comment]
This is in leap, I just ran into it.
