### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by GlueWear** [tloncorp/landscape-apps#2494]
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at Zo.get (http://localhost/apps/groups/assets/@urbit/api.e47df60a.js:3:14684)
    at Af (http://localhost/apps/groups/assets/index.52dc4675.js:45:44540)
    at Kl (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (http://localhost/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
```

**Comment by jamesacklin** [comment]
What were you doing when you encountered this error?

**Comment by jamesacklin** [comment]
Tracking internally as LAND-461
