### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by Maidyo3030** [tloncorp/landscape-apps#2579]
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at Mfe (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:179:1215)
    at Pt (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:179:779)
    at Lde.getSource (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:179:17320)
    at Lde.removeSource (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:179:17831)
    at https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:179:29535
    at dC (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:60:3303)
    at ZS (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:60:5327)
    at G$ (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:62:3887)
    at e.unstable_runWithPriority (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:47:3927)
    at jc (https://finmes-mosheb.urbox.one/apps/grid/assets/index.4b023d30.js:58:38631)
```

**Comment by jamesacklin** [comment]
Tracking internally as LAND-476

**Comment by jamesacklin** [comment]
Unable to reproduce, closing for now.
