### ISSUE TITLE
Cannot read properties of undefined (reading 'quips')

### ISSUE THREAD

**Issue by TheatrumMundi** [tloncorp/landscape-apps#2597]
```
TypeError: Cannot read properties of undefined (reading 'quips')
    at q8 (https://paclux-dansyl.tlon.network/apps/groups/assets/index.b18819a0.js:48:221856)
    at Kl (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
    at _r (https://paclux-dansyl.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38494)
```

**Comment by jamesacklin** [comment]
Fixed by #2630
