### ISSUE TITLE
leap: Cannot read properties of undefined (reading '')

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#2602]
1. Open Leap with hotkey
2. Start typing a search term
3. 💥 

macOS 13.4 (22F66)
Brave [Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (arm64)]
Using PWA

```
TypeError: Cannot read properties of undefined (reading '')
    at Xf (apps/groups/assets/index.92553d4b.js:44:8030)
    at apps/groups/assets/index.92553d4b.js:44:8138
    at _ (apps/groups/assets/index.92553d4b.js:44:26750)
    at apps/groups/assets/index.92553d4b.js:44:27000
    at Array.filter (<anonymous>)
    at apps/groups/assets/index.92553d4b.js:44:26990
    at Object.Jd [as useMemo] (apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:57586)
    at f.useMemo (apps/groups/assets/@tlon/sigil-js.4fa95bd4.js:12:5789)
    at ir (apps/groups/assets/index.92553d4b.js:44:26519)
    at Vm (apps/groups/assets/index.92553d4b.js:48:282456)
```

**Comment by jamesacklin** [comment]
Fixed by #2604
