### ISSUE TITLE
Opening Leap with "Cmd K" results in error: Cannot read properties of undefined (reading '')

### ISSUE THREAD

**Issue by urcades** [tloncorp/landscape-apps#2607]
What it says on the tin:

```
TypeError: Cannot read properties of undefined (reading '')
    at bd (https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:44:7316)
    at https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:44:7965
    at H (https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:44:25530)
    at https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:44:25782
    at Array.filter (<anonymous>)
    at https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:44:25772
    at Object.js [as useMemo] (https://fabled-faster.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:57536)
    at f.useMemo (https://fabled-faster.tlon.network/apps/talk/assets/@tlon/sigil-js.4fa95bd4.js:12:5789)
    at Cr (https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:44:25302)
    at F3 (https://fabled-faster.tlon.network/apps/talk/assets/index.d8ed719f.js:48:135640)
```

**Comment by jamesacklin** [comment]
Fixed by #2604
