### ISSUE TITLE
Invalid integer: quipCount

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape-apps#2618]
**Describe the bug, optionally with screenshots**
I tried to make a new post in a notebook channel in a secret group. The channel has public write permissions. I am an admin in the group. The post is a single markdown block with a LOT of text in it. After I hit "post", it took a while to post, so I refreshed my `%groups` while it was still spinning. Somehow, this has completely borked the channel for me. Now when I attempt to open this particular notebook channel in the group, I get the following error:

```
Error: Invalid integer: quipCount
    at Cu (http://localhost:8080/apps/groups/assets/index.51e9b51d.js:1:24086)
    at ce (http://localhost:8080/apps/groups/assets/index.51e9b51d.js:1:24487)
    at u (http://localhost:8080/apps/groups/assets/index.51e9b51d.js:1:3434)
    at http://localhost:8080/apps/groups/assets/index.51e9b51d.js:36:81780
    at Array.map (<anonymous>)
    at _h (http://localhost:8080/apps/groups/assets/index.51e9b51d.js:36:81761)
    at L7 (http://localhost:8080/apps/groups/assets/index.51e9b51d.js:48:229069)
    at Kl (http://localhost:8080/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (http://localhost:8080/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (http://localhost:8080/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
```

It's worth noting that the other members in the group can access both the channel and post without issue.

**To Reproduce**
1. Go to a notebook channel
2. Make a new post with a LOT of text in a Markdown block
3. Click on 'Save'
4. Mash the refresh button
5. See error (I'm not actually sure if it's reproducible and I don't want to try outside of a moon)

**Expected behavior**
Refreshing at an untimely moment during posting/loading big notebook posts doesn't bork the ship's channel state.

**Additional context:**
- Ship type = planet
- Instance type = self-hosted locally
- OS/browser = Chromium-based browser on Pop!_OS 22.04

**Comment by jamesacklin** [comment]
Fixed by #2630
