### ISSUE TITLE
Group crashes after editing and saving a note

### ISSUE THREAD

**Issue by MagnusdeAart** [tloncorp/landscape-apps#2627]
When i save a note in a notebook and edit it, save it and edit it again, and then save it, i get this error and cannot use the whole group anymore. This is the second time this has happened in two different groups now. :)

```
TypeError: Cannot read properties of undefined (reading 'quips')
    at q8 (https://magnus-nimpur.third.earth/apps/groups/assets/index.b18819a0.js:48:221856)
    at Kl (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
    at _r (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38494)
```

**Comment by jamesacklin** [comment]
Fixed by #2630
