### ISSUE TITLE
Latest groups update: Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by fighet-parnet** [tloncorp/landscape-apps#2634]
```
TypeError: Cannot read properties of undefined (reading 'title')
    at Pl (https://fighet-parnet.tlon.network/apps/groups/assets/index.d35d1683.js:48:181697)
    at Kl (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
```
I'm getting the above stacktrace when I try to open groups. This was working ~15 minutes ago, then stopped.

**Comment by jamesacklin** [comment]
Tracking internally as LAND-601

Fixed by #2635
