### ISSUE TITLE
Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by MagnusdeAart** [tloncorp/landscape-apps#2640]
```
TypeError: Cannot read properties of undefined (reading 'description')
    at Pl (https://magnus-nimpur.third.earth/apps/groups/assets/index.ad30a98e.js:48:182309)
    at Kl (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://magnus-nimpur.third.earth/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
```

**Comment by jamesacklin** [comment]
Thanks; can you share what you were doing at the time?
