### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by nghiepmmo8888** [tloncorp/landscape-apps#2657]
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at F4e (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:251:44843)
    at At (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:251:44416)
    at U5e.getSource (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:251:60867)
    at U5e.removeSource (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:251:61378)
    at https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:251:73064
    at aM (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:87:3303)
    at uP (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:87:5327)
    at fj (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:89:3879)
    at e.unstable_runWithPriority (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:74:3993)
    at Ku (https://wanweb-figsum.tlon.network/apps/grid/assets/index.78c07bfe.js:85:38575)
```

**Comment by jamesacklin** [comment]
@nghiepmmo8888 Thanks. What were you doing when you experienced this error?

**Comment by jamesacklin** [comment]
Closing as duplicate of #2579.
