### ISSUE TITLE
Invalid integer: quipCount

### ISSUE THREAD

**Issue by sigilante** [tloncorp/landscape-apps#2660]
A failed Publish post leads to an inability to post to that channel at all.

```
Error: Invalid integer: quipCount
    at Cu (http://100.94.113.44:8080/apps/groups/assets/index.ad30a98e.js:1:24087)
    at ce (http://100.94.113.44:8080/apps/groups/assets/index.ad30a98e.js:1:24488)
    at u (http://100.94.113.44:8080/apps/groups/assets/index.ad30a98e.js:1:3435)
    at http://100.94.113.44:8080/apps/groups/assets/index.ad30a98e.js:36:81758
    at Array.map (<anonymous>)
    at zh (http://100.94.113.44:8080/apps/groups/assets/index.ad30a98e.js:36:81739)
    at $7 (http://100.94.113.44:8080/apps/groups/assets/index.ad30a98e.js:48:229163)
    at Kl (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
```

**Comment by jamesacklin** [comment]
Fixed by #2654
