### ISSUE TITLE
Invalid integer: quipCount

### ISSUE THREAD

**Issue by ilyakooo0** [tloncorp/landscape-apps#2667]
```
Error: Invalid integer: quipCount
    at Cu (https://urbit.iko.soy/apps/groups/assets/index.ad30a98e.js:1:24087)
    at ce (https://urbit.iko.soy/apps/groups/assets/index.ad30a98e.js:1:24488)
    at u (https://urbit.iko.soy/apps/groups/assets/index.ad30a98e.js:1:3435)
    at https://urbit.iko.soy/apps/groups/assets/index.ad30a98e.js:36:81758
    at Array.map (<anonymous>)
    at zh (https://urbit.iko.soy/apps/groups/assets/index.ad30a98e.js:36:81739)
    at $7 (https://urbit.iko.soy/apps/groups/assets/index.ad30a98e.js:48:229163)
    at Kl (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (https://urbit.iko.soy/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
```

**Comment by patosullivan** [comment]
Could you provide the output of `+vats %groups, =verb &`? What were you trying to do at the time?

**Comment by jamesacklin** [comment]
Also fixed by #2654, hasn't been release yet (ETA ~2023.7.5)
