### ISSUE TITLE
Invalid integer: quipCount

### ISSUE THREAD

**Issue by rashlo** [tloncorp/landscape-apps#2674]
```
Error: Invalid integer: quipCount
    at Cu (https://motdeg-bintul.tlon.network/apps/groups/assets/index.ad30a98e.js:1:24087)
    at ce (https://motdeg-bintul.tlon.network/apps/groups/assets/index.ad30a98e.js:1:24488)
    at u (https://motdeg-bintul.tlon.network/apps/groups/assets/index.ad30a98e.js:1:3435)
    at https://motdeg-bintul.tlon.network/apps/groups/assets/index.ad30a98e.js:36:81758
    at Array.map (<anonymous>)
    at zh (https://motdeg-bintul.tlon.network/apps/groups/assets/index.ad30a98e.js:36:81739)
    at $7 (https://motdeg-bintul.tlon.network/apps/groups/assets/index.ad30a98e.js:48:229163)
    at Kl (https://motdeg-bintul.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at mf (https://motdeg-bintul.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:8723)
    at pf (https://motdeg-bintul.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
```

**Comment by jamesacklin** [comment]
We believe we've fixed this in the latest release; can you confirm it's fixed on your end?

**Comment by rashlo** [comment]
Yup, everything is now good on my end 👍
