### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by mrblack193** [tloncorp/landscape-apps#2676]
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at I4e (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:251:44843)
    at Ot (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:251:44416)
    at y0 (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:251:73911)
    at M3e (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:251:77004)
    at O3e (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:251:77337)
    at axe (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:252:28050)
    at GS (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:85:52997)
    at kP (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:89:8819)
    at bP (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:89:951)
    at fj (https://rinres-fodser.tlon.network/apps/grid/assets/index.ccb9cc79.js:89:879)
```

**Comment by patosullivan** [comment]
Hey, thanks for the error report. What were you doing at the moment this occurred?
