### ISSUE TITLE
Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by wca4a** [tloncorp/landscape-apps#2679]
```
TypeError: Cannot read properties of undefined (reading 'value')
    at f.compare (https://malmur-halmex.tlon.network/apps/groups/assets/index.ad30a98e.js:1:13312)
    at https://malmur-halmex.tlon.network/apps/groups/assets/index.ad30a98e.js:36:56137
    at e.indexOf (https://malmur-halmex.tlon.network/apps/groups/assets/index.ad30a98e.js:36:47937)
    at e.get (https://malmur-halmex.tlon.network/apps/groups/assets/index.ad30a98e.js:36:48603)
    at e.get (https://malmur-halmex.tlon.network/apps/groups/assets/index.ad30a98e.js:36:37919)
    at Ax (https://malmur-halmex.tlon.network/apps/groups/assets/index.ad30a98e.js:45:40812)
    at Kl (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://malmur-halmex.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
```

**Comment by wca4a** [comment]
I replied to a message in groups, then i deleted that reply and when i did
that it also deleted the original message.
