### ISSUE TITLE
Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by samuelwfrank** [tloncorp/landscape-apps#2681]
```
TypeError: Cannot read properties of undefined (reading 'description')
    at Pl (https://todset-partug.tlon.network/apps/groups/assets/index.ad30a98e.js:48:182309)
    at Kl (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
    at yg (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:875)
    at rn (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:730)
    at sl (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:21:10884)
    at https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:38716
    at e.unstable_runWithPriority (https://todset-partug.tlon.network/apps/groups/assets/react-beautiful-dnd.fde4d763.js:8:3811)
```

**Comment by jamesacklin** [comment]
@samuelwfrank Thanks; what were you doing when you encountered this error?

**Comment by samuelwfrank** [comment]
I was leaving some groups/channels. I can’t remember the precise action
that set this off, unfortunately.
