### ISSUE TITLE
Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by ml-sudocode** [tloncorp/landscape-apps#2685]
```
TypeError: Cannot read properties of undefined (reading 'match')
    at https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:161:302404
    at Object.useMemo (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:58:59118)
    at Jt.useMemo (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:40:5905)
    at ik (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:161:302390)
    at dx (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:58:53173)
    at eB (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:62:8847)
    at XS (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:62:957)
    at M$ (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:62:885)
    at j1 (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:62:738)
    at u7 (https://tanned-sipped.third.earth/apps/grid/assets/index.8a26ea07.js:60:10912)
```

**Comment by jamesacklin** [comment]
@ml-sudocode Thanks for the bug report. Can you detail what you were doing at the time in Landscape when you received this error?
