### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by mrblack193** [tloncorp/landscape-apps#2745]
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at W4e (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:251:45288)
    at At (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:251:44861)
    at y0 (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:251:74356)
    at F3e (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:251:77449)
    at P3e (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:251:77782)
    at dxe (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:252:28049)
    at OS (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:85:52997)
    at _P (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:89:8819)
    at kP (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:89:951)
    at pj (https://rinres-fodser.tlon.network/apps/grid/assets/index.bf362b99.js:89:879)
```

**Comment by jamesacklin** [comment]
Hi -- can you give us a little more information about your setup? Browser/OS/VPN/other connection details?
