### ISSUE TITLE
Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by fighet-parnet** [tloncorp/landscape-apps#2748]
```
TypeError: Cannot read properties of undefined (reading 'description')
    at Mu (https://fighet-parnet.tlon.network/apps/groups/assets/index.734f7ae1.js:62:182474)
    at Xl (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:19:52884)
    at Xa (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:19:62361)
    at hf (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:23:9604)
    at vf (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:23:947)
    at wg (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:23:875)
    at rn (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:23:730)
    at cl (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:21:10884)
    at https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:19:38716
    at e.unstable_runWithPriority (https://fighet-parnet.tlon.network/apps/groups/assets/react-beautiful-dnd.e0ad5b6a.js:8:3811)
```

Not the first time I've had this issue.

**Comment by fighet-parnet** [comment]
This is seemingly caused randomly just as I use groups. Once it occurs, groups becomes unusable on that computer for awhile.
