### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by babnta** [tloncorp/landscape-apps#2752]
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at W4e (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:251:45288)
    at At (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:251:44861)
    at J5e.getSource (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:251:61312)
    at J5e.removeSource (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:251:61823)
    at https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:251:73509
    at hM (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:87:3303)
    at gP (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:87:5327)
    at gj (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:89:3879)
    at e.unstable_runWithPriority (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:74:3993)
    at Qu (https://rosrus-mirteb.tlon.network/apps/grid/assets/index.bf362b99.js:85:38575)
```

**Comment by jamesacklin** [comment]
Hi -- can you give us a little more information about your setup? Browser/OS/VPN/other connection details?

**Comment by babnta** [comment]
ohh, I use Chrome/Win10, no VPN. I have cleared the site's cache and reloaded it but it still doesn't work. Now I have upgraded a new machine (win 11) and tried to login again with web. The results seem to remain unchanged. 
bonus: I'm from Vietnam
