### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by sigilante** [tloncorp/landscape-apps#2814]
This error occurred on editing a notebook.  It seems to make the group unusable from that point.

  App: Groups
  Version: undefined
  Vere Version: 2.11
  Hash: undefined
  Synced From: undefined
  Location: /apps/groups/groups/~magbel/in-tenebris-silva/channels/diary/~magbel/scholia-cotidie--daily-notes-

  ```
RangeError: Invalid time value
    at Et (http://100.94.113.44:8080/apps/groups/assets/date-fns-12fc9f89.js:1:24958)
    at Fm (http://100.94.113.44:8080/apps/groups/assets/index-6a134eea.js:81:78974)
    at Tu (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:30:19470)
    at Rp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:32:43828)
    at kp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:32:39610)
    at vh (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:32:39538)
    at yo (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:32:39393)
    at Vl (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:32:35786)
    at bp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:32:34737)
    at x (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-8ff486ca.js:17:1561)
```

**Comment by jamesacklin** [comment]
Thanks, tracking internally as LAND-797

**Comment by neonfuz** [comment]
I had this happen to me while an app was installing, and it went away after the app completed installation.
