### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by nohokum** [tloncorp/landscape-apps#2832]
App: Groups
  Version: 4.4.1
  Vere Version: 2.11
  Hash: 0v1e.tcpr8.0f10a.v3pbd.oelin.ibrq6.0u0os.4dsu6.kldg3.vv877.h3ter
  Synced From: ~sogryp-dister-dozzod-dozzod
  Location: /apps/groups/groups/~bidbel/a/channels/diary/~bidbel/mars-review-of-books--issue-one/edit/170141184506119879120156272529932025856

  ```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.onExit (https://bidbel.urbit.studio/apps/groups/assets/index-9786b591.js:71:36538)
    at Object.destroy (https://bidbel.urbit.studio/apps/groups/assets/index-9786b591.js:71:22817)
    at Gl.destroyPluginViews (https://bidbel.urbit.studio/apps/groups/assets/@tiptap/core-015873ec.js:8:42886)
    at Gl.updatePluginViews (https://bidbel.urbit.studio/apps/groups/assets/@tiptap/core-015873ec.js:8:43046)
    at Gl.updateStateInner (https://bidbel.urbit.studio/apps/groups/assets/@tiptap/core-015873ec.js:8:42383)
    at ri.updateState (https://bidbel.urbit.studio/apps/groups/assets/diary-add-note-5b4627a7.js:1:20604)
    at D7.registerPlugin (https://bidbel.urbit.studio/apps/groups/assets/@tiptap/core-015873ec.js:86:2320)
    at https://bidbel.urbit.studio/apps/groups/assets/index-9786b591.js:66:5064
    at $o (https://bidbel.urbit.studio/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:24187)
    at Ft (https://bidbel.urbit.studio/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:42186)
```

**Comment by jamesacklin** [comment]
Fixed in the next coming release.
