### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#2878]
I tried to edit the title a notebook post that i just posted, caught this error:
 
  App: Groups
  Version: 4.5.1
  Vere Version: undefined [It's 2.12, I just updated this week]
  Hash: 0vb.j5372.9otds.2vmst.s6ioe.ga2nb.4g63j.e9gj4.4atif.1f03j.isia9
  Synced From: ~doznec-dozzod-marnus
  Location: /apps/groups/groups/~dalten/aera/channels/diary/~sicdev-pilnup/meeting-notes---agenda

  ```
RangeError: Invalid time value
    at Et (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/date-fns-900bec8f.js:1:24958)
    at g0 (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/index-3bf90a3d.js:82:37100)
    at Mu (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:30:19470)
    at Bp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:43828)
    at Tp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:39610)
    at gh (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:39538)
    at So (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:39393)
    at ql (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:35786)
    at kp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:32:34737)
    at x (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-00fbdda6.js:17:1561)
```

**Comment by thelifeandtimes** [comment]
this from the Brave PWA. Gave it a refresh and retried and it worked...

**Comment by jamesacklin** [comment]
OK, thanks. We fixed this and I'm glad it eventually worked; I'll keep the issue open. Bump if you hit it again.

**Comment by sigilante** [comment]
I have hit this again after a recent Markdown post.  I'm locked out of my group by it.

  App: Groups
  Version: undefined
  Vere Version: undefined
  Hash: undefined
  Synced From: undefined
  Location: /apps/groups/groups/~magbel/in-tenebris-silva/channels/diary/~magbel/scholia-cotidie--daily-notes-

  ```
RangeError: Invalid time value
    at Et (http://100.94.113.44:8080/apps/groups/assets/date-fns-70b49252.js:1:24958)
    at g0 (http://100.94.113.44:8080/apps/groups/assets/index-f8f2a5da.js:82:37157)
    at Mu (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
    at kp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:34737)
    at x (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:17:1561)
```

**Comment by jamesacklin** [comment]
Seen, thanks.
