### ISSUE TITLE
Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#2924]
App: Groups
  Version: undefined
  Vere Version: undefined
  Hash: undefined
  Synced From: undefined
  Location: /apps/groups/groups/~ligbel/vaporware-public/channels/chat/~fogpeg-ligbel/vapor-forum

  ```
TypeError: Cannot read properties of undefined (reading 'start')
    at H4 (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/index-3b149c71.js:120:246692)
    at Mu (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
    at kp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:34737)
    at x (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:17:1561)
    at MessagePort.oe (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:17:1928)
```

opened a newly created group, hosted by ~ligbel with channels hosted by ~fogpeg-ligbel. All running 412. ~sarlev-sarsen was in the group when a single chat channel existed. I created a few more chat channels and notebooks and then when trying to visit I experience this crash.

**Comment by jamesacklin** [comment]
Just fixed in an upcoming build -- will release through the early adopter channel ASAP
