### ISSUE TITLE
Unhandled message type

### ISSUE THREAD

**Issue by sigilante** [tloncorp/landscape-apps#2931]
Attempting to create a notebook through Markdown is crashing in an unexpected way.  I've attempted to clean up the text in question but it continues to give me this odd error and then remove the notebook.

  App: Groups
  Version: 4.5.1
  Vere Version: undefined
  Hash: 0v18.j9pe2.l4k1j.lkrsq.rr1je.ngbh9.pvodq.bo6e0.bkv8g.l34sl.186g8
  Synced From: ~bosdev-dozzod-marnus
  Location: /apps/groups/groups/~magbel/in-tenebris-silva/channels/diary/~magbel/scholia-magistrorum-marginal-notes-2104/note/170141184506449702394138479480709591334

  ```
Error: Unhandled message type: {"listing":{"list":{"type":"ordered","items":[{"item":["Restrict technological development.",{"break":null}]},{"item":["Ensure that there does not exist a large population of actors representing a wide and recognizably human distribution of motives.",{"break":null}]},{"item":["Establish extremely effective preventive policing.",{"break":null}]},{"item":["Establish effective global governance",{"break":null}]}],"contents":[]}}}
    at $n (http://100.94.113.44:8080/apps/groups/assets/index-f8f2a5da.js:72:47379)
    at Mu (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
    at Ac (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:36588)
    at Jr (http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:3258)
    at http://100.94.113.44:8080/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:34123
```

**Comment by sigilante** [comment]
I think it's caused by an enumerated list inside a quote block, maybe?

**Comment by jamesacklin** [comment]
Interesting, will try to reproduce

**Comment by sigilante** [comment]
I can provide the source text to you directly if you like.  I've reproduced this several times from my current instance in multiple notebooks (on the same ship tho).

**Comment by sigilante** [comment]
It looks like that is the issue.  This fails:

```
> 1. Restrict technological development.
> 2. Ensure that there does not exist a large population of actors representing a wide and recognizably human distribution of motives.
> 3. Establish extremely effective preventive policing.
> 4. Establish effective global governance
```

while this works:

```
> Restrict technological development.
> Ensure that there does not exist a large population of actors representing a wide and recognizably human distribution of motives.
> Establish extremely effective preventive policing.
> Establish effective global governance
```
