### ISSUE TITLE
Cannot read properties of null (reading 'memo')

### ISSUE THREAD

**Issue by nismut-tamwep** [tloncorp/landscape-apps#2948]
```
TypeError: Cannot read properties of null (reading 'memo')
    at Lw (https://nismut-tamwep.startram.io/apps/talk/assets/index.6d7465ae.js:48:18501)
    at Ko (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at eo (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:62311)
    at ea (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:9576)
    at Js (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:935)
    at Qf (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:866)
    at sn (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:725)
    at mo (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:21:10863)
    at https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:38697
    at e.unstable_runWithPriority (https://nismut-tamwep.startram.io/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:8:3835)
```

**Comment by patosullivan** [comment]
Can you share the output of `+vats %groups, =verb &`?
