### ISSUE TITLE
Unhandled message type: {"header":{"tag":"h3",...

### ISSUE THREAD

**Issue by sigilante** [tloncorp/landscape-apps#3055]
It looks like Groups pages choke on header lines other than `h1` maybe?

---

  App: Groups
  Version: undefined
  Vere Version: 
  Hash: undefined
  Synced From: undefined
  Location: /apps/groups/groups/~magbel/in-tenebris-silva/channels/diary/~magbel/scholia-cotidie--daily-notes-/note/170141184506537112992258515129405450223

  ```
Error: Unhandled message type: {"header":{"tag":"h3","content":["Coexistence under contemporary niche theory"]}}
    at Hn (http://100.94.113.44:8081/apps/groups/assets/index-d62c0078.js:139:48323)
    at Mu (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
    at kp (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:34737)
    at x (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:17:1561)
    at MessagePort.oe (http://100.94.113.44:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:17:1928)
```

**Comment by patosullivan** [comment]
Hey, fyi, I was unable to repro this. Is it still an issue for you?

**Comment by sigilante** [comment]
I'd have to see if I can repro the original Markdown.  (I altered it to make it work.)  So we can close now.
