### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gordoncc** [tloncorp/landscape-apps#3097]
Got the latest update on my Tlon hosted ship and got the following:

```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at p (https://sidseg-hosbus.tlon.network/apps/talk/assets/index.c65579f1.js:44:6832)
    at a (https://sidseg-hosbus.tlon.network/apps/talk/assets/index.c65579f1.js:48:123554)
    at https://sidseg-hosbus.tlon.network/apps/talk/assets/index.c65579f1.js:48:125791
    at Object.js [as useMemo] (https://sidseg-hosbus.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:57536)
    at f.useMemo (https://sidseg-hosbus.tlon.network/apps/talk/assets/@tlon/sigil-js.4fa95bd4.js:12:5789)
    at Bf (https://sidseg-hosbus.tlon.network/apps/talk/assets/index.c65579f1.js:48:125779)
    at Ko (https://sidseg-hosbus.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at eo (https://sidseg-hosbus.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:62311)
    at ea (https://sidseg-hosbus.tlon.network/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:9576)
```

**Comment by patosullivan** [comment]
Thanks for the bug report. Can you tell us what screen you were looking at when this occurred?

**Comment by mrozanski** [comment]
Closing for now, if more details are added and issue is still valid we can reopen.
