### ISSUE TITLE
Error when opening %talk: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by JohnRillos** [tloncorp/landscape-apps#3108]
```
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at p (https://REDACTED/apps/talk/assets/index.7d0a0b17.js:48:14580)
    at a (https://REDACTED/apps/talk/assets/index.7d0a0b17.js:48:122772)
    at https://REDACTED/apps/talk/assets/index.7d0a0b17.js:48:124934
    at Object.js [as useMemo] (https://REDACTED/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:57536)
    at f.useMemo (https://REDACTED/apps/talk/assets/@tlon/sigil-js.4fa95bd4.js:12:5789)
    at yf (https://REDACTED/apps/talk/assets/index.7d0a0b17.js:48:124922)
    at Ko (https://REDACTED/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:52865)
    at eo (https://REDACTED/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:19:62311)
    at ea (https://REDACTED/apps/talk/assets/react-beautiful-dnd.a94a7f90.js:23:9576)
```

**Comment by JohnRillos** [comment]
Never mind, I think I just had to hard-refresh after the big update
