### ISSUE TITLE
Cannot destructure property 'reference' of 'l' as it is null.

### ISSUE THREAD

**Issue by kyepskee** [tloncorp/landscape-apps#3116]
This message popped up while browsing %groups, I can't really supply more info, because I don't have any, but maybe it's helpful  

App: Groups
  Version: 5.0.0
  Vere Version: undefined
  Hash: 0v1s.7ep87.aiap9.3roit.05gnb.tcjct.8ogng.jo78m.sbd8k.ghh61.cn9dr
  Synced From: ~lander-dister-dozzod-dozzod
  Location: /apps/groups/groups/~minder-folden/valeria-city/channels/heap/~minder-folden/the-fridge

  ```
TypeError: Cannot destructure property 'reference' of 'l' as it is null.
    at B0 (http://192.168.0.39:8081/apps/groups/assets/index-6afd79f0.js:63:71670)
    at rF (http://192.168.0.39:8081/apps/groups/assets/index-6afd79f0.js:139:41770)
    at Mu (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Fl (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:3134)
    at vp (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:2350)
    at Bp (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:47142)
    at Tp (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (http://192.168.0.39:8081/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
```

**Comment by darighost** [comment]
This should be fixed as soon as the next release comes out, thanks to https://github.com/tloncorp/landscape-apps/pull/3099. 

See:
https://github.com/tloncorp/landscape-apps/issues/3101
https://github.com/tloncorp/landscape-apps/issues/3100
https://github.com/tloncorp/landscape-apps/issues/3095

If you urgently need to access that channel, you can do so by running Groups using this repo directly. If you need help doing that, just let me know, I'd be glad to help!

**Comment by darighost** [comment]
@kyepskee The new version of Groups has been released, and this should be fixed.

I tested it myself by joining the same channel where you experienced this issue (The Fridge from Valeria City).

This is the post which I believe was causing the issue: /1/chan/heap/~minder-folden/the-fridge/curio/170141184506535435038523850898330877952

![Screenshot 2023-12-12 at 9 42 29](https://github.com/tloncorp/landscape-apps/assets/104947308/94bf50b4-a519-4f1a-af06-21e6feb5c753)

As you can see, the new version of Groups allows access The Fridge without this error occurring.
