### ISSUE TITLE
Unhandled message type: {"listing":{"list":{"type":"ordered","items":[{"item":["GET ALERT","...~~~A BUNCH OF MARKDOWN~~~ 

### ISSUE THREAD

**Issue by thelifeandtimes** [tloncorp/landscape-apps#3125]
**Describe the bug, optionally with screenshots**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

**To Reproduce**
1. Go to a notebook post that was put up prior to Groups 2 as raw markdown
2. Click on Edit
3. See that it transforms into markdown with a bunch of escape characters and weird spaces.
4. Try to remove all of those, Save the post.
5. Try to read the post and see the error.

**Expected behavior**
I expect my notebook to be able to parse the markdown within it.

**Additional context:**
- Ship type: Planet
- Instance type: Self-Hosted
- OS/browser: Brave PWA
![Uploading image.png…]()
```
Error: Unhandled message type: {"listing":{"list":{"type":"ordered","items":[{"item":["GET ALERT","We must be alert to trigger neuroplasticity (later, sleep completes the neuroplasticity/learning process). Getting alert involves many mechanisms but mainly the release of epinephrine (adrenaline) in the brain and body. One simple way to become more alert is 25-30 deep breaths (inhales through the nose, and exhales through the mouth). Then exhale your air and hold your breath with lungs empty for 15-60 seconds. Then inhale once and hold your breath. But don’t force the breath hold; start to breathe normally immediately once you feel the impulse to breathe. Whether you rely on caffeine or not (I certainly do in the early portion of the day), try this prior to a learning bout.",{"break":null}]},{"item":["GET FOCUSED","Mental focus follows visual focus. To increase your level of focus on the task you are about to do, stare at a point on a wall or screen, or object for 30-60 seconds before starting (You can blink as needed). You’ll be surprised how this takes a bit of effort—that ‘effort’ you feel is “top-down” attentional engagement and reflects the activity of neural circuits involving acetylcholine release in the brain, and other mechanisms too of course. Then move into the task at hand. Expect your mental focus to flicker on and off, especially at the start of a work/learning bout. [Obviously, having your phone off and out of the room and web browsers closed or limited to essential tabs only (or even better, the internet turned off) can help.]",{"break":null}]},{"item":["GENERATE REPETITIONS","Perform the maximum number of repetitions you safely can in a given learning bout. For some types of learning, “repetitions” will be actual repeats of something- learning scales of music, for instance. We progress linearly for other types of learning by repeating the same process, such as reading or doing math problems. Regardless, the same principle holds; work to repeat the process a bit faster than is reflexive for you. This helps the mind from drifting off task and naturally keeps you alert. Will you make errors? Of course, which leads to #4.",{"break":null}]},{"item":["EXPECT & EMBRACE ERRORS","Provided they don’t comprise safety, errors during learning are terrific because they increase activation of the neural circuits that increase alertness. It makes sense, right? If you perform something correctly, why should your brain take notice? When we make errors, it feels “stressful,” but that is just an increase in attention that puts us in a much better place to perform and execute learning-related behaviors the next trial—meaning on the next attempt. Computational modeling data suggests that an error rate of ~15% may be optimal and can help determine how difficult we should make a task. But don’t worry too much about those specifics. Instead, keep doing repetitions and when you mess up, capitalize on it by doing another attempt (and another) while your forebrain is in that maximally attentive state.",{"break":null}]},{"item":["INSERT MICRO-REST INTERVALS (AT RANDOM)","This is a non-obvious way to increase repetitions and learn faster. Studies (in humans) have shown that when we are trying to learn something, if we pause every so often for 10seconds and do nothing during the pause, neurons in the hippocampus and cortex—areas of the brain involved in learning and memory, engage the same patterns of neural activity that occurred during the actual activity of reading, musical practice, skill training, etc. but 10X faster—meaning you get 10X neural repetitions completed during the pause. These “gap-effects” are similar to what happens in a deep sleep. The takeaway: randomly introduce 10 second pauses during learning. “How often?” I get asked. A ratio of approximately 1 pause per every 2 minutes of learning is good but remember, distributed at random, so not every 2 minutes on the minute.",{"break":null}]},{"item":["USE RANDOM INTERMITTENT REWARD","The neural circuits that control rewards (all of which are brain chemical rewards, by the way) are closely tethered to the circuits that control motivation and the desire to pursue things, including learning. The question of how often to reward ourselves or others in order to keep motivation high is simple: make it random and intermittent. This is what casinos do to keep people gambling. It works. Predictable rewards lose their motivational impact quickly.",{"break":null}]},{"item":["LIMIT LEARNING SESSIONS TO 90 MINUTES",{"break":null}]},{"item":["AFTER A LEARNING BOUT, DO A NSDR (NON-SLEEP DEEP REST) PROTOCOL",{"break":null}]},{"item":["GET QUALITY & SUFFICIENTLY LONG DEEP SLEEP THAT NIGHT (& THE NEXT, & THE NEXT…)",{"break":null}]}],"contents":[]}}}
    at Zn (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/index-ed5cba58.js:139:48840)
    at Mu (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
    at Ac (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:36588)
    at Jr (https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:3258)
    at https://sarlev-sarsen.rooftopdao.io/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:34123
```

**Comment by thelifeandtimes** [comment]
After refreshing the PWA, the markdown has reverted but I am able to get into the notebook post without issue.
