### ISSUE TITLE
Pasting bold or italicized text into AddCurioModal crashes Groups

### ISSUE THREAD

**Issue by darighost** [tloncorp/landscape-apps#3128]
Earlier tonight, I created a gallery and tried to paste some text into it. The text happened to be bold in the original HTML document where I copied it

However, I got an error:

![Screenshot 2023-12-15 at 1 57 48](https://github.com/tloncorp/landscape-apps/assets/104947308/8a5603a6-b937-4add-a0bc-b68f41e5000f)

And some additional info about the error from the console...

```
The above error occurred in the <AddCurioModal> component:

    at AddCurioModal (https://127.0.0.1:3000/apps/groups/src/heap/AddCurioModal.tsx:32:3)
    at div
    at div
    at ChannelHeader (https://127.0.0.1:3000/apps/groups/src/channels/ChannelHeader.tsx:30:3)
    at https://127.0.0.1:3000/apps/groups/src/heap/HeapHeader.tsx:35:3
    at header
    at div
    at Layout (https://127.0.0.1:3000/apps/groups/src/components/Layout/Layout.tsx:19:3)
    at HeapChannel (https://127.0.0.1:3000/apps/groups/src/heap/HeapChannel.tsx:42:3)
    at RenderedRoute (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:2760:5)
    at Outlet (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:3031:26)
    at GroupChannel (https://127.0.0.1:3000/apps/groups/src/groups/GroupChannel.tsx:22:3)
    at RenderedRoute (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:2760:5)
    at Outlet (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:3031:26)
    at div
    at Groups (https://127.0.0.1:3000/apps/groups/src/groups/Groups.tsx:33:20)
    at RenderedRoute (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:2760:5)
    at RenderedRoute (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:2760:5)
    at Outlet (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:3031:26)
    at div
    at GroupsNav (https://127.0.0.1:3000/apps/groups/src/nav/GroupsNav.tsx:79:20)
    at RenderedRoute (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:2760:5)
    at Routes (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:3091:5)
    at GroupsRoutes (https://127.0.0.1:3000/apps/groups/src/app.tsx:540:3)
    at DragAndDropProvider (https://127.0.0.1:3000/apps/groups/src/logic/DragAndDropContext.tsx:34:3)
    at ChatInputFocusProvider (https://127.0.0.1:3000/apps/groups/src/logic/ChatInputFocusContext.tsx:25:3)
    at LeapProvider (https://127.0.0.1:3000/apps/groups/src/components/Leap/useLeap.tsx:53:3)
    at div
    at App (https://127.0.0.1:3000/apps/groups/src/app.tsx:1370:20)
    at Provider (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-QIM4CPYN.js?v=ca8e0197:52:15)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=ca8e0197:2253:11)
    at Router (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-25M27VLL.js?v=ca8e0197:3038:15)
    at BrowserRouter (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/react-router-dom.js?v=ca8e0197:249:5)
    at ErrorBoundary2 (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/react-error-boundary.js?v=ca8e0197:35:35)
    at RoutedApp (https://127.0.0.1:3000/apps/groups/src/app.tsx:1477:47)
    at PostHogProvider (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/posthog-js_react.js?v=ca8e0197:16:21)
    at SafeAreaProvider (https://127.0.0.1:3000/apps/groups/src/logic/SafeAreaContext.tsx:29:3)
    at QueryClientProvider (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/chunk-J75YY6UW.js?v=ca8e0197:2658:3)
    at PersistQueryClientProvider (https://127.0.0.1:3000/apps/groups/node_modules/.vite/deps/@tanstack_react-query-persist-client.js?v=ca8e0197:136:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary2.
```

The same error occurs when I try italic text.

Okay, so when content is styled a certain way (bold, italic, probably others), it gets noticed and the json structure of the content in the editor is different. 

When it tries to render this stylized content, I think it triggers something that changes the state, which rerenders, and so on and so forth, leading to the error.

**Comment by darighost** [comment]
What the `clipboardData` looks like normally:

```json
[
    {
        "type": "paragraph",
        "content": [
            {
                "type": "text",
                "text": "dsdsdsdsdsddsddsdsds"
            }
        ]
    }
]
```

What it looks like when things go wrong:

```json
[
    {
        "type": "paragraph",
        "content": [
            {
                "type": "text",
                "marks": [
                    {
                        "type": "bold"
                    }
                ],
                "text": "Sylvia Plath"
            }
        ]
    }
]
```

I hope this is helpful!

**Comment by darighost** [comment]
Ship: ~motluc-nammex
Host: Tlon

Chrome on MacOS
