### ISSUE TITLE
Invalid integer: ~fansub-patmud

### ISSUE THREAD

**Issue by Viktor-WWWW** [tloncorp/landscape-apps#3151]
I just tried to open an old notification. 

App: Groups
  Version: 5.2.0
  Vere Version: undefined
  Hash: 0v1j.a2lpu.el328.2oqjo.42k60.ki7t9.ij7l8.4sous.do23p.lagcp.pdek5
  Synced From: ~sogryp-dister-dozzod-dozzod
  Location: /apps/groups/groups/~nibset-napwyn/tlon/channels/chat/~nibset-napwyn/intros/message/~fansub-patmud/170.141.184.506.479.821.389.625.399.695.201.884.176

  ```
Error: Invalid integer: ~fansub-patmud
    at Ce (https://fansub-patmud.tlon.network/apps/groups/assets/index-d551d3a3.js:1:24427)
    at ee (https://fansub-patmud.tlon.network/apps/groups/assets/index-d551d3a3.js:1:24832)
    at d (https://fansub-patmud.tlon.network/apps/groups/assets/index-d551d3a3.js:1:3483)
    at Jg (https://fansub-patmud.tlon.network/apps/groups/assets/index-d551d3a3.js:140:122546)
    at Mu (https://fansub-patmud.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (https://fansub-patmud.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (https://fansub-patmud.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (https://fansub-patmud.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (https://fansub-patmud.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (https://fansub-patmud.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
```

**Comment by youfoundron** [comment]
Recently encountered this same issue:

  App: Groups
  Version: 5.2.0
  Vere Version: undefined
  Hash: 0vb8p5e.u3nck.fm1uh.j6hhl.h2rcs.2fmlp.9iqh5.s08pn.q9oei.35pea
  Synced From: ~sogryp-dister-dozzod-dozzod
  Location: /apps/groups/groups/~hiddev-dannut/new-hooniverse/channels/chat/~hiddev-dannut/hooniversity--scheduled-classes-5052/message/170141184506570472258907461185014071296

  ```
Ce@https://urbit.youfoundron.com/apps/groups/assets/index-d551d3a3.js:1:23998
ee@https://urbit.youfoundron.com/apps/groups/assets/index-d551d3a3.js:1:24832
d@https://urbit.youfoundron.com/apps/groups/assets/index-d551d3a3.js:1:3483
Jg@https://urbit.youfoundron.com/apps/groups/assets/index-d551d3a3.js:140:125033
Mu@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470
Fl@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:3134
Bp@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:44601
Tp@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39612
gh@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39540
So@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393
ql@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786
Ac@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:36588
Jr@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:3258
Ae/<@https://urbit.youfoundron.com/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:34123

```

**Comment by youfoundron** [comment]
looks like your drag-n-drop component is acting up
