### ISSUE TITLE
Invalid integer: NaN is not a valid exponent.

### ISSUE THREAD

**Issue by agrislis** [tloncorp/landscape-apps#3157]
App: Groups
  Version: undefined
  Vere Version: 
  Hash: undefined
  Synced From: undefined
  Location: /apps/groups/groups/~tommur-dostyn/tlon-studio/channels/chat/~tommur-dostyn/support/message/~dozreg-toplud/170.141.184.506.420.740.976.095.923.573.410.416.820

  ```
Error: Invalid integer: NaN is not a valid exponent.
    at Se (https://wicneb-holnep.tlon.network/apps/groups/assets/index-51522f66.js:1:24126)
    at ee (https://wicneb-holnep.tlon.network/apps/groups/assets/index-51522f66.js:1:24832)
    at d (https://wicneb-holnep.tlon.network/apps/groups/assets/index-51522f66.js:1:3483)
    at r0 (https://wicneb-holnep.tlon.network/apps/groups/assets/index-51522f66.js:144:124403)
    at Mu (https://wicneb-holnep.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:30:19470)
    at Bp (https://wicneb-holnep.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:43828)
    at Tp (https://wicneb-holnep.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39610)
    at gh (https://wicneb-holnep.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39538)
    at So (https://wicneb-holnep.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:39393)
    at ql (https://wicneb-holnep.tlon.network/apps/groups/assets/react-beautiful-dnd-5ffc626c.js:32:35786)
```

**Comment by jamesacklin** [comment]
@agrislis Thanks. Do you happen to remember what you clicked or where this broken link came from?

**Comment by agrislis** [comment]
If a remember right I got this error when I tried to open PWA Groups app after some time without activity. Reinstall helped me with it.
