### ISSUE TITLE
t.postMessage is not a function

### ISSUE THREAD

**Issue by zmy567** [tloncorp/landscape-apps#3192]
App: Groups
  Version: undefined
  Vere Version: undefined
  Hash: undefined
  Synced From: undefined
  Location: /apps/groups/groups/~tommur-dostyn/tlon-studio/channels/heap/~tommur-dostyn/references/curio/170141184506559142634180261138223071232

  ```
TypeError: t.postMessage is not a function
    at mS (https://dasden-sovtyc.tlon.network/apps/groups/assets/index-2565c406.js:28:1322)
    at ad (https://dasden-sovtyc.tlon.network/apps/groups/assets/index-2565c406.js:28:1364)
    at https://dasden-sovtyc.tlon.network/apps/groups/assets/index-2565c406.js:154:191754
    at $o (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:32:24187)
    at Ft (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:32:42186)
    at Ac (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:32:36475)
    at Jr (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:30:3258)
    at hh (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:32:41094)
    at tt (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:32:40096)
    at kp (https://dasden-sovtyc.tlon.network/apps/groups/assets/react-beautiful-dnd-3d2c43b3.js:32:35586)
```
Dropped like a megaton hammer. My my 🤓
I am otherwise ready to reply how much that was for just a dump truck.
Just post.
Remote content blocked on the Tlon account system from the media/photo link. User intent is post textual response. Result is not possible, so next the intent is enable remote content to sync in media channels from groups.

**Comment by lukestiles** [comment]
@zak-myb are you still seeing this error? I am not able to reproduce it.

**Comment by zak-myb** [comment]
@lukestiles so sorry for my delayed response! let me describe what I'd done, since I have uninstalled and reinstalled the app after I had deleted the account responsible as the local overlays left it with markers like ~undefined and would no longer load the data right.
Now I'm here with my app reinstalled on the Moto 5G Stylus but my account would not be registered without explicitly conversing with support@tlon-corporation.com to register and try again.
