### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by JEJEKR** [tloncorp/landscape-apps#3266]
```
TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at l5e (http://localhost/apps/landscape/assets/index.d0ba7f74.js:251:47672)
    at Ot (http://localhost/apps/landscape/assets/index.d0ba7f74.js:251:47245)
    at v3e.getSource (http://localhost/apps/landscape/assets/index.d0ba7f74.js:251:63696)
    at v3e.removeSource (http://localhost/apps/landscape/assets/index.d0ba7f74.js:251:64207)
    at http://localhost/apps/landscape/assets/index.d0ba7f74.js:251:75893
    at gM (http://localhost/apps/landscape/assets/index.d0ba7f74.js:87:3303)
    at xP (http://localhost/apps/landscape/assets/index.d0ba7f74.js:87:5327)
    at kj (http://localhost/apps/landscape/assets/index.d0ba7f74.js:89:3879)
    at e.unstable_runWithPriority (http://localhost/apps/landscape/assets/index.d0ba7f74.js:74:3993)
    at Qu (http://localhost/apps/landscape/assets/index.d0ba7f74.js:85:38575)
```

**Comment by JEJEKR** [comment]
rebooted and resolved :)
